//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registerStudents.Almacen {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoUsuario", Namespace="http://schemas.datacontract.org/2004/07/WebApplication1")]
    [System.SerializableAttribute()]
    public partial class InfoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userRequerimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userSexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userApellido {
            get {
                return this.userApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.userApellidoField, value) != true)) {
                    this.userApellidoField = value;
                    this.RaisePropertyChanged("userApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userDepartamento {
            get {
                return this.userDepartamentoField;
            }
            set {
                if ((this.userDepartamentoField.Equals(value) != true)) {
                    this.userDepartamentoField = value;
                    this.RaisePropertyChanged("userDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userDireccion {
            get {
                return this.userDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.userDireccionField, value) != true)) {
                    this.userDireccionField = value;
                    this.RaisePropertyChanged("userDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userEmail {
            get {
                return this.userEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.userEmailField, value) != true)) {
                    this.userEmailField = value;
                    this.RaisePropertyChanged("userEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userRequerimiento {
            get {
                return this.userRequerimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.userRequerimientoField, value) != true)) {
                    this.userRequerimientoField = value;
                    this.RaisePropertyChanged("userRequerimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userSexo {
            get {
                return this.userSexoField;
            }
            set {
                if ((object.ReferenceEquals(this.userSexoField, value) != true)) {
                    this.userSexoField = value;
                    this.RaisePropertyChanged("userSexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Almacen.IAlmacen")]
    public interface IAlmacen {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlmacen/getForm", ReplyAction="http://tempuri.org/IAlmacen/getFormResponse")]
        void getForm(registerStudents.Almacen.InfoUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlmacen/getForm", ReplyAction="http://tempuri.org/IAlmacen/getFormResponse")]
        System.Threading.Tasks.Task getFormAsync(registerStudents.Almacen.InfoUsuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlmacenChannel : registerStudents.Almacen.IAlmacen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenClient : System.ServiceModel.ClientBase<registerStudents.Almacen.IAlmacen>, registerStudents.Almacen.IAlmacen {
        
        public AlmacenClient() {
        }
        
        public AlmacenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void getForm(registerStudents.Almacen.InfoUsuario usuario) {
            base.Channel.getForm(usuario);
        }
        
        public System.Threading.Tasks.Task getFormAsync(registerStudents.Almacen.InfoUsuario usuario) {
            return base.Channel.getFormAsync(usuario);
        }
    }
}
